name: Push Event Workflow

on: push

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Packages
        run: pip install pytest

      - name: Run tests
        run: pytest tests.py # Update the path to your tests file

      - name: Debug
        run: |
          pwd
          ls -R
        shell: bash
